name: flutter_commons_generator
description: CLI application to generate common dart code used in Flutter projects.
version: 1.0.0

publish_to: none

executables:
  flutter_commons_generator:

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  code_coverage: ^1.4.0
  lints: ^1.0.0
  test: ^1.20.1

dependencies:
  args: ^2.3.0
  basic_utils: ^3.9.4
  code_generator:
    git: https://github.com/gustavo-hillesheim/dart_code_generator.git
  dart_style: ^2.2.1
