name: flutter_commons_core
description: Package containing common code used in Flutter projects.
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  equatable: ^2.0.0
  fpdart: ^0.0.1

dev_dependencies:
  lints: ^1.0.0
